// src/app/(gestion)/finances/page.tsx
import type { Metadata } from "next";
import Link from "next/link";
import { asc, desc, eq } from "drizzle-orm";
import { getDb } from "@/db";
import { etudiants, inscriptions } from "@/db/schema";
import { Flash } from "@/components/flash";
import { BoutonEnvoi, Formulaire } from "@/components/formulaire";
import { LigneCliquable } from "@/components/ligne-cliquable";
import { SelectFiltre } from "@/components/selecteur";
import { BadgePaiement, param } from "@/components/ui";
import { exigerRole } from "@/lib/auth/current";
import { montantEnRetard, montantNet, soldeRestant, statutPaiement, totalVerse } from "@/lib/domain/calculs";
import { anneeCourante, formatDate, formatMru, formatNombre } from "@/lib/format";
import { anneesRecentes } from "@/lib/requetes";
import { FINANCE } from "@/lib/roles";
import { MODES_PAIEMENT } from "@/lib/validation";
import { actionEcheance, actionSituation, actionVersement } from "./actions";

export const metadata: Metadata = { title: "Finances" };

const champ = "rounded-lg text-gray-900 text-xs";

export default async function Finances({ searchParams }: PageProps<"/finances">) {
  const user = await exigerRole(FINANCE);
  const sp = await searchParams;
  const onglet = param(sp.tab) === "reversement" ? "reversement" : "etudiants";
  const db = getDb();

  const liste = await db.query.etudiants.findMany({
    orderBy: [asc(etudiants.nom), asc(etudiants.prenom)],
    with: { inscriptions: { orderBy: desc(inscriptions.id), limit: 1, with: { versements: true, echeances: true } } },
  });

  const etudiantId = Number(param(sp.etudiant)) || null;
  const selection = etudiantId
    ? await db.query.etudiants.findFirst({
        where: eq(etudiants.id, etudiantId),
        with: {
          inscriptions: {
            orderBy: [desc(inscriptions.createdAt), desc(inscriptions.id)],
            with: { formation: true, annee: true, versements: true, echeances: true },
          },
        },
      })
    : null;
  // L'inscription demandée doit appartenir à l'étudiant sélectionné.
  const inscriptionId = Number(param(sp.inscription)) || null;
  const dossier = selection
    ? (selection.inscriptions.find((i) => i.id === inscriptionId) ?? selection.inscriptions[0] ?? null)
    : null;

  const annees = await anneesRecentes();
  const anneeChoisie = Number(param(sp.annee_reversement)) || anneeCourante(annees)?.id;
  const toutes = await db.query.inscriptions.findMany({ with: { versements: true } });
  const synthese = annees.map((a) => {
    const groupe = toutes.filter((i) => i.idAnneeAcademique === a.id);
    const du = groupe.reduce((s, i) => s + montantNet(i), 0);
    const encaisse = groupe.reduce((s, i) => s + totalVerse(i), 0);
    return {
      ...a,
      nb: groupe.length,
      du,
      encaisse,
      statut: du > 0 && encaisse >= du ? "Soldé" : encaisse > 0 ? "Partiel" : "Impayé",
    };
  });
  const carte = synthese.find((a) => a.id === anneeChoisie);

  const lienOnglet = (o: string) => {
    const q = new URLSearchParams();
    if (selection) q.set("etudiant", String(selection.id));
    if (o === "reversement") q.set("tab", "reversement");
    return `/finances?${q.toString()}`;
  };

  return (
    <>
      <h1 className="text-xl font-bold text-insec mb-4">Finances</h1>
      <Flash />
      <div className="flex flex-wrap gap-2 mb-4">
        {[
          ["etudiants", "Étudiants"],
          ["reversement", "Synthèse annuelle"],
        ].map(([o, l]) => (
          <Link
            key={o}
            href={lienOnglet(o)}
            aria-current={onglet === o ? "page" : undefined}
            className={`px-4 py-2 rounded-lg text-sm font-medium ${onglet === o ? "bg-insec text-white" : "bg-white text-gray-600 border"}`}
          >
            {l}
          </Link>
        ))}
      </div>

      {onglet === "etudiants" ? (
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
          <div className="lg:col-span-2 bg-white rounded-xl shadow overflow-x-auto h-fit">
            <table className="w-full text-sm border-collapse">
              <thead>
                <tr className="bg-insec text-white">
                  <th className="p-3 text-left">Étudiant</th>
                  <th className="p-3 text-left">Restant</th>
                  <th className="p-3 text-left">Statut</th>
                </tr>
              </thead>
              <tbody>
                {liste.length ? (
                  liste.map((e) => {
                    const i = e.inscriptions[0];
                    return (
                      <LigneCliquable
                        key={e.id}
                        href={`/finances?etudiant=${e.id}`}
                        className={`border-b hover:bg-gray-50 ${selection?.id === e.id ? "bg-blue-50" : ""}`}
                      >
                        <td className="p-3 text-gray-900">
                          <Link href={`/finances?etudiant=${e.id}`}>
                            {e.nom} {e.prenom}
                          </Link>
                        </td>
                        <td className="p-3 text-gray-700">{formatNombre(i ? soldeRestant(i) : 0)}</td>
                        <td className="p-3">
                          <BadgePaiement statut={i ? statutPaiement(i) : "Non inscrit"} />
                        </td>
                      </LigneCliquable>
                    );
                  })
                ) : (
                  <tr>
                    <td colSpan={3} className="p-6 text-center text-gray-400">
                      Aucun étudiant.
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
            <p className="text-xs text-gray-400 p-3">Cliquez sur un étudiant pour ouvrir son dossier.</p>
          </div>

          {selection && (
            <div className="bg-insec text-white rounded-xl shadow p-5 h-fit">
              <p className="text-amber-400 text-xs font-bold uppercase tracking-wide">
                Dossier — {selection.nom} {selection.prenom}
              </p>
              <div className="flex flex-wrap gap-2 mt-3">
                {selection.inscriptions.map((d) => (
                  <Link
                    key={d.id}
                    href={`/finances?etudiant=${selection.id}&inscription=${d.id}`}
                    className={`text-xs px-2 py-1 rounded ${dossier?.id === d.id ? "bg-amber-500 text-white" : "bg-white/10 text-blue-100"}`}
                  >
                    {d.formation?.code} {d.annee?.libelle}
                  </Link>
                ))}
              </div>

              {dossier ? (
                <>
                  <p className="text-xs text-blue-200 mt-4">Montant brut</p>
                  <p className="text-2xl font-bold">{formatMru(dossier.montantDu)}</p>
                  <p className="text-xs text-blue-200 mt-3">Remise · Montant net</p>
                  <p className="text-sm">
                    <span className="text-amber-300">- {formatNombre(dossier.montantRemise)}</span> ·{" "}
                    <strong>{formatMru(montantNet(dossier))}</strong>
                  </p>
                  <p className="text-xs text-blue-200 mt-4">Total versé</p>
                  <p className="text-lg font-bold text-green-400">{formatMru(totalVerse(dossier))}</p>
                  <p className="text-xs text-blue-200 mt-4">Solde restant (calculé)</p>
                  <p className="text-lg font-bold text-amber-400">{formatMru(soldeRestant(dossier))}</p>
                  {montantEnRetard(dossier) > 0 && (
                    <p className="mt-2 rounded bg-red-500/20 p-2 text-xs text-red-200">En retard : {formatMru(montantEnRetard(dossier))}</p>
                  )}

                  <Formulaire
                    action={actionSituation.bind(null, dossier.id)}
                    erreurs="premiere"
                    className="border-t border-blue-400/30 mt-4 pt-4 space-y-2"
                  >
                    <div className="flex gap-2">
                      <label className="flex-1 text-xs text-blue-200">
                        Montant brut
                        <input type="number" name="montant_du" min={0} defaultValue={dossier.montantDu} required className={`w-full mt-1 ${champ}`} />
                      </label>
                      <label className="flex-1 text-xs text-blue-200">
                        Remise
                        <input type="number" name="montant_remise" min={0} defaultValue={dossier.montantRemise} required className={`w-full mt-1 ${champ}`} />
                      </label>
                    </div>
                    <textarea
                      name="note_financiere"
                      defaultValue={dossier.noteFinanciere ?? ""}
                      placeholder="Note financière interne"
                      aria-label="Note financière interne"
                      className={`w-full ${champ}`}
                    />
                    <BoutonEnvoi className="w-full bg-amber-500 text-white text-xs font-medium px-3 py-2 rounded-lg">Mettre à jour</BoutonEnvoi>
                  </Formulaire>

                  <div className="border-t border-blue-400/30 mt-4 pt-4">
                    <p className="text-xs text-blue-200 mb-2">Échéancier</p>
                    {dossier.echeances.length ? (
                      [...dossier.echeances]
                        .sort((a, b) => a.dateEcheance.localeCompare(b.dateEcheance))
                        .map((e) => (
                          <div key={e.id} className="flex justify-between text-xs bg-white/10 rounded px-2 py-1 mb-1">
                            <span>
                              {e.libelle} · {formatDate(e.dateEcheance)}
                            </span>
                            <strong>{formatNombre(e.montant)}</strong>
                          </div>
                        ))
                    ) : (
                      <p className="text-xs text-blue-200">Aucune échéance.</p>
                    )}
                    <Formulaire action={actionEcheance.bind(null, dossier.id)} erreurs="premiere" className="grid grid-cols-2 gap-2 mt-2">
                      <input name="libelle" placeholder="Ex. 1re tranche" aria-label="Libellé de l’échéance" required className={`rounded ${champ}`} />
                      <input type="number" name="montant" min={1} placeholder="Montant" aria-label="Montant de l’échéance" required className={`rounded ${champ}`} />
                      <input type="date" name="date_echeance" aria-label="Date d’échéance" required className={`rounded ${champ}`} />
                      <BoutonEnvoi className="bg-white/10 rounded text-xs">+ Échéance</BoutonEnvoi>
                    </Formulaire>
                  </div>

                  <div className="border-t border-blue-400/30 mt-4 pt-4">
                    <p className="text-xs text-blue-200 mb-2">Derniers versements</p>
                    <div className="space-y-2 mb-4">
                      {dossier.versements.length ? (
                        [...dossier.versements]
                          .sort((a, b) => b.dateVersement.localeCompare(a.dateVersement) || b.id - a.id)
                          .map((v) => (
                            <div key={v.id}>
                              <div className="flex items-center justify-between bg-white/10 rounded-lg px-3 py-2 text-xs">
                                <span>{formatDate(v.dateVersement)}</span>
                                <span>{formatNombre(v.montant)}</span>
                                <span className={v.statut === "Validée" ? "text-green-400" : "text-amber-400"}>{v.statut}</span>
                              </div>
                              <p className="text-[10px] text-blue-200 px-2">
                                {v.numeroRecu ? (
                                  <a href={`/pdf/recus/${v.id}`} className="underline">
                                    {v.numeroRecu}
                                  </a>
                                ) : (
                                  "Sans reçu"
                                )}{" "}
                                · {v.modePaiement}
                                {v.reference ? ` · ${v.reference}` : ""}
                              </p>
                            </div>
                          ))
                      ) : (
                        <p className="text-xs text-blue-200">Aucun versement.</p>
                      )}
                    </div>

                    <Formulaire action={actionVersement.bind(null, dossier.id)} erreurs="premiere" reinitialiser className="space-y-2">
                      <p className="text-xs text-blue-200">Ajouter un versement</p>
                      <div className="flex gap-2">
                        <input type="number" name="montant" min={1} placeholder="Montant" aria-label="Montant du versement" required className={`w-1/2 ${champ}`} />
                        <input type="date" name="date_versement" aria-label="Date du versement" required className={`w-1/2 ${champ}`} />
                      </div>
                      <select name="statut" aria-label="Statut du versement" required className={`w-full ${champ}`}>
                        <option value="Validée">Validée</option>
                        <option value="En attente">En attente</option>
                      </select>
                      <div className="flex gap-2">
                        <select name="mode_paiement" aria-label="Mode de paiement" className={`w-1/2 ${champ}`}>
                          {MODES_PAIEMENT.map((m) => (
                            <option key={m}>{m}</option>
                          ))}
                        </select>
                        <input name="reference" placeholder="Référence (facultatif)" aria-label="Référence" className={`w-1/2 ${champ}`} />
                      </div>
                      <textarea name="note" placeholder="Note (facultatif)" aria-label="Note" className={`w-full ${champ}`} />
                      <BoutonEnvoi className="w-full bg-amber-500 hover:bg-amber-600 text-white text-xs font-medium px-3 py-2 rounded-lg">
                        + Ajouter le versement
                      </BoutonEnvoi>
                    </Formulaire>
                  </div>
                </>
              ) : (
                <p className="text-sm text-blue-200 mt-4">
                  Cet étudiant n’a pas encore de formation/année assignée.{" "}
                  {user.role !== "finance" && (
                    <Link href={`/etudiants/${selection.id}/inscriptions/create`} className="underline text-amber-400">
                      Créer une inscription
                    </Link>
                  )}
                </p>
              )}
            </div>
          )}
        </div>
      ) : (
        <div>
          <div className="mb-4 flex items-center gap-3">
            <span className="text-sm text-gray-600">Année académique :</span>
            <SelectFiltre
              nom="annee_reversement"
              libelle="Année académique"
              valeur={anneeChoisie}
              options={annees.map((a) => ({ valeur: a.id, libelle: a.libelle }))}
            />
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-4">
            <div className="bg-white rounded-xl shadow p-4">
              <p className="text-xs text-gray-500">Étudiants concernés</p>
              <p className="text-xl font-bold text-insec">{carte?.nb ?? 0}</p>
            </div>
            <div className="bg-white rounded-xl shadow p-4">
              <p className="text-xs text-gray-500">Frais nets facturés</p>
              <p className="text-xl font-bold text-insec">{formatMru(carte?.du ?? 0)}</p>
            </div>
            <div className="bg-white rounded-xl shadow p-4">
              <p className="text-xs text-gray-500">Encaissé auprès des étudiants</p>
              <p className="text-xl font-bold text-green-600">{formatMru(carte?.encaisse ?? 0)}</p>
            </div>
          </div>
          <div className="bg-white rounded-lg shadow overflow-x-auto">
            <table className="w-full text-sm border-collapse">
              <thead>
                <tr className="bg-insec text-white">
                  <th className="p-3 text-left">Année académique</th>
                  <th className="p-3 text-left">Étudiants</th>
                  <th className="p-3 text-left">Montant dû</th>
                  <th className="p-3 text-left">Encaissé</th>
                  <th className="p-3 text-left">Statut</th>
                </tr>
              </thead>
              <tbody>
                {synthese.filter((a) => a.nb > 0).length ? (
                  synthese
                    .filter((a) => a.nb > 0)
                    .map((a) => (
                      <tr key={a.id} className="border-b">
                        <td className="p-3">{a.libelle}</td>
                        <td className="p-3">{a.nb}</td>
                        <td className="p-3">{formatNombre(a.du)}</td>
                        <td className="p-3">{formatNombre(a.encaisse)}</td>
                        <td className="p-3">
                          <BadgePaiement statut={a.statut} />
                        </td>
                      </tr>
                    ))
                ) : (
                  <tr>
                    <td colSpan={5} className="p-6 text-center text-gray-400">
                      Aucune donnée.
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
        </div>
      )}
    </>
  );
}

// src/vues/Finances.vue
<script setup lang="ts">
import { MODES_PAIEMENT, montantEnRetard, montantNet, soldeRestant, statutPaiement } from '@shared/domaine';
import { collection, orderBy, query, where } from 'firebase/firestore';
import { computed, reactive, ref, watch, watchEffect } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { appeler } from '../api';
import BadgeStatut from '../composants/BadgeStatut.vue';
import Chargement from '../composants/Chargement.vue';
import { indexer, useRequete } from '../donnees';
import { telecharger } from '../fichiers';
import { db } from '../firebase';
import { aujourdhui, date, montant } from '../format';
import { useFormulaire } from '../formulaire';
import { notifier } from '../notifications';
import { useReferentiel } from '../referentiel';
import { aRole } from '../session';
import type { Etudiant, Inscription, Versement } from '../types';

const route = useRoute();
const router = useRouter();
const { formation, annee, annees } = useReferentiel();
const onglet = ref<'etudiants' | 'synthese'>(route.query.onglet === 'synthese' ? 'synthese' : 'etudiants');
const { donnees: etudiants, chargement, erreur } = useRequete<Etudiant>(() => query(collection(db, 'etudiants'), orderBy('nom')));
const { donnees: inscriptions } = useRequete<Inscription>(() => collection(db, 'inscriptions'));
const parInscription = computed(() => indexer(inscriptions.value));
const recherche = ref('');
const etudiantsFiltres = computed(() => {
    const t = recherche.value.trim().toLowerCase();
    return etudiants.value.filter((e) => !t || `${e.nom} ${e.prenom} ${e.email}`.toLowerCase().includes(t));
});

const etudiantId = computed(() => (typeof route.query.etudiant === 'string' ? route.query.etudiant : null));
const selectionne = computed(() => etudiants.value.find((e) => e.id === etudiantId.value) ?? null);
const emailEtudiantValide = computed(() => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(selectionne.value?.email?.trim() ?? ''));
const dossiers = computed(() => inscriptions.value.filter((i) => i.etudiantId === etudiantId.value).sort((a, b) => b.ordre - a.ordre));
const inscription = computed(() => {
    const demandee = typeof route.query.inscription === 'string' ? route.query.inscription : null;
    return dossiers.value.find((i) => i.id === demandee) ?? dossiers.value[0] ?? null;
});
const { donnees: versementsBruts } = useRequete<Versement>(() =>
    inscription.value ? query(collection(db, 'versements'), where('inscriptionId', '==', inscription.value.id)) : null,
);
const versements = computed(() => [...versementsBruts.value].sort((a, b) => b.dateVersement.localeCompare(a.dateVersement)));

const ouvrir = (etudiant: string, dossier?: string) => router.replace({ query: { etudiant, ...(dossier ? { inscription: dossier } : {}) } });

// Formulaires du dossier sélectionné.
const { envoi, erreurs, soumettre } = useFormulaire();
const situation = reactive({ montantDu: 0, montantRemise: 0, noteFinanciere: '' });
watch(inscription, (i) => {
    if (i) Object.assign(situation, { montantDu: i.montantDu, montantRemise: i.montantRemise, noteFinanciere: i.noteFinanciere ?? '' });
}, { immediate: true });
const echeance = reactive({ libelle: '', montant: null as number | null, dateEcheance: '' });
const versement = reactive({ montant: null as number | null, dateVersement: aujourdhui(), statut: 'Validée', modePaiement: 'Espèces', reference: '', note: '' });

async function executer(operation: string, donnees: object, apres?: () => void) {
    const resultat = await soumettre(() => appeler(operation, donnees));
    if (!resultat) return;
    notifier(resultat.message ?? 'Enregistré.');
    apres?.();
}
const majSituation = () => executer('modifierSituationFinanciere', { id: inscription.value!.id, ...situation });
const ajouterEcheance = () =>
    executer('ajouterEcheance', { inscriptionId: inscription.value!.id, ...echeance }, () => Object.assign(echeance, { libelle: '', montant: null, dateEcheance: '' }));
const ajouterVersement = () =>
    executer('ajouterVersement', { inscriptionId: inscription.value!.id, ...versement }, () => Object.assign(versement, { montant: null, reference: '', note: '' }));

async function envoyerDocument(type: 'facture' | 'recu', id: string, libelle: string, destinataire: string) {
    const email = destinataire.trim();
    const nom = `${selectionne.value?.prenom ?? ''} ${selectionne.value?.nom ?? ''}`.trim() || 'étudiant';
    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
        notifier('Adresse e-mail absente ou invalide. Corrigez-la dans la fiche de l’étudiant avant l’envoi.');
        return;
    }
    if (!window.confirm(`Envoyer ${libelle} en PDF à ${nom} (${email}) ? Le document contient des informations personnelles.`)) return;
    const resultat = await soumettre(() => appeler('envoyerDocumentParEmail', { type, id }));
    if (resultat) notifier(resultat.message ?? 'Document envoyé par e-mail.');
}

// Synthèse annuelle des frais facturés et encaissés.
const anneeSynthese = ref('');
watchEffect(() => {
    if (!anneeSynthese.value && annees.value[0]) anneeSynthese.value = annees.value[0].id;
});
const synthese = computed(() =>
    annees.value.map((a) => {
        const liste = inscriptions.value.filter((i) => i.anneeId === a.id);
        const du = liste.reduce((t, i) => t + montantNet(i), 0);
        const encaisse = liste.reduce((t, i) => t + (i.totalVerse ?? 0), 0);
        return { id: a.id, libelle: a.libelle, nb: liste.length, du, encaisse, statut: du > 0 && encaisse >= du ? 'Soldé' : encaisse > 0 ? 'Partiel' : 'Impayé' };
    }),
);
const carte = computed(() => synthese.value.find((s) => s.id === anneeSynthese.value));
const millions = (v = 0) => (v / 1_000_000).toLocaleString('fr-FR', { minimumFractionDigits: 1, maximumFractionDigits: 1 });
</script>

<template>
    <h1 class="mb-4 text-xl font-bold text-insec">Finances</h1>
    <div class="mb-4 flex gap-2">
        <button :class="['bouton', onglet === 'etudiants' ? 'bg-insec text-white' : 'border bg-white text-gray-600']" @click="onglet = 'etudiants'">Étudiants</button>
        <button :class="['bouton', onglet === 'synthese' ? 'bg-insec text-white' : 'border bg-white text-gray-600']" @click="onglet = 'synthese'">Synthèse annuelle</button>
    </div>

    <Chargement :chargement="chargement" :erreur="erreur">
        <div v-if="onglet === 'etudiants'" class="grid grid-cols-1 gap-4 lg:grid-cols-3">
            <div class="overflow-hidden rounded-xl bg-white shadow lg:col-span-2">
                <div class="p-3"><input v-model="recherche" type="search" placeholder="Rechercher un étudiant…" class="champ" aria-label="Rechercher" /></div>
                <div class="max-h-[70vh] overflow-y-auto">
                    <table class="tableau">
                        <thead class="sticky top-0"><tr><th>Étudiant</th><th>Restant</th><th>Statut</th></tr></thead>
                        <tbody>
                            <tr
                                v-for="e in etudiantsFiltres"
                                :key="e.id"
                                :class="['cursor-pointer hover:bg-gray-50', e.id === etudiantId ? 'bg-blue-50' : '']"
                                @click="ouvrir(e.id)"
                            >
                                <td class="text-gray-900">{{ e.nom }} {{ e.prenom }}</td>
                                <td class="text-gray-700">{{ montant(e.derniere && parInscription.get(e.derniere.inscriptionId) ? soldeRestant(parInscription.get(e.derniere.inscriptionId)!) : 0) }}</td>
                                <td>
                                    <BadgeStatut :statut="e.derniere && parInscription.get(e.derniere.inscriptionId) ? statutPaiement(parInscription.get(e.derniere.inscriptionId)!) : 'Non inscrit'" />
                                </td>
                            </tr>
                            <tr v-if="!etudiantsFiltres.length"><td colspan="3" class="p-6 text-center text-gray-400">Aucun étudiant.</td></tr>
                        </tbody>
                    </table>
                </div>
                <p class="p-3 text-xs text-gray-400">Cliquez sur un étudiant pour ouvrir son dossier.</p>
            </div>

            <div v-if="selectionne" class="rounded-xl bg-insec p-5 text-white shadow">
                <p class="text-xs font-bold tracking-wide text-amber-400 uppercase">Dossier — {{ selectionne.nom }} {{ selectionne.prenom }}</p>
                <div class="mt-3 flex flex-wrap gap-2">
                    <button
                        v-for="d in dossiers"
                        :key="d.id"
                        :class="['cursor-pointer rounded px-2 py-1 text-xs', inscription?.id === d.id ? 'bg-amber-500 text-white' : 'bg-white/10 text-blue-100']"
                        @click="ouvrir(selectionne.id, d.id)"
                    >{{ formation(d.formationId)?.code }} {{ annee(d.anneeId)?.libelle }}</button>
                </div>

                <template v-if="inscription">
                    <p class="mt-4 text-xs text-blue-200">Montant brut</p>
                    <p class="text-2xl font-bold">{{ montant(inscription.montantDu) }} MRU</p>
                    <p class="mt-3 text-xs text-blue-200">Remise · Montant net</p>
                    <p class="text-sm"><span class="text-amber-300">- {{ montant(inscription.montantRemise) }}</span> · <strong>{{ montant(montantNet(inscription)) }} MRU</strong></p>
                    <p class="mt-4 text-xs text-blue-200">Total versé</p>
                    <p class="text-lg font-bold text-green-400">{{ montant(inscription.totalVerse) }} MRU</p>
                    <p class="mt-4 text-xs text-blue-200">Solde restant (calculé)</p>
                    <p class="text-lg font-bold text-amber-400">{{ montant(soldeRestant(inscription)) }} MRU</p>
                    <button
                        v-if="aRole('admin', 'super_admin')"
                        class="mt-3 w-full rounded-lg border border-white/30 bg-white/10 px-3 py-2 text-sm font-semibold text-white hover:bg-white/20"
                        @click="soumettre(() => telecharger('genererPdf', { type: 'facture', id: inscription.id }))"
                    >Télécharger la facture PDF</button>
                    <button
                        v-if="aRole('admin', 'super_admin')"
                        type="button"
                        class="mt-2 w-full rounded-lg border border-white/30 px-3 py-2 text-sm text-blue-50 hover:bg-white/10"
                        :disabled="envoi || !emailEtudiantValide"
                        @click="envoyerDocument('facture', inscription.id, 'la facture', selectionne.email)"
                    >Envoyer la facture par e-mail</button>
                    <p v-if="emailEtudiantValide" role="status" class="mt-2 text-xs text-blue-100">Destinataire : {{ selectionne.email }}</p>
                    <p v-else class="mt-2 rounded bg-amber-400/15 p-2 text-xs text-amber-100">
                        Adresse e-mail absente ou invalide. <RouterLink :to="`/etudiants/${selectionne.id}/modifier`" class="underline">Corriger la fiche étudiant</RouterLink> avant l’envoi.
                    </p>
                    <p v-if="montantEnRetard(inscription) > 0" class="mt-2 rounded bg-red-500/20 p-2 text-xs text-red-200">En retard : {{ montant(montantEnRetard(inscription)) }} MRU</p>

                    <form class="mt-4 space-y-2 border-t border-blue-400/30 pt-4" @submit.prevent="majSituation">
                        <div class="flex gap-2">
                            <label class="flex-1 text-xs text-blue-200">Montant brut <input v-model.number="situation.montantDu" type="number" min="0" class="mt-1 w-full rounded-lg text-xs text-gray-900" required /></label>
                            <label class="flex-1 text-xs text-blue-200">Remise <input v-model.number="situation.montantRemise" type="number" min="0" class="mt-1 w-full rounded-lg text-xs text-gray-900" required /></label>
                        </div>
                        <p v-if="erreurs.montantRemise" class="text-xs text-red-200">{{ erreurs.montantRemise }}</p>
                        <textarea v-model="situation.noteFinanciere" placeholder="Note financière interne" class="w-full rounded-lg text-xs text-gray-900" maxlength="2000"></textarea>
                        <button class="bouton w-full bg-amber-500 py-2 text-xs text-white" :disabled="envoi">Mettre à jour</button>
                    </form>

                    <div class="mt-4 border-t border-blue-400/30 pt-4">
                        <p class="mb-2 text-xs text-blue-200">Échéancier</p>
                        <div v-for="e in inscription.echeances" :key="e.id" class="mb-1 flex justify-between rounded bg-white/10 px-2 py-1 text-xs">
                            <span>{{ e.libelle }} · {{ date(e.dateEcheance) }}</span><strong>{{ montant(e.montant) }}</strong>
                        </div>
                        <p v-if="!inscription.echeances?.length" class="text-xs text-blue-200">Aucune échéance.</p>
                        <form class="mt-2 grid grid-cols-2 gap-2" @submit.prevent="ajouterEcheance">
                            <input v-model="echeance.libelle" placeholder="Ex. 1re tranche" class="rounded text-xs text-gray-900" required maxlength="100" />
                            <input v-model.number="echeance.montant" type="number" min="1" placeholder="Montant" class="rounded text-xs text-gray-900" required />
                            <input v-model="echeance.dateEcheance" type="date" class="rounded text-xs text-gray-900" required aria-label="Date d’échéance" />
                            <button class="cursor-pointer rounded bg-white/10 text-xs" :disabled="envoi">+ Échéance</button>
                        </form>
                    </div>

                    <div class="mt-4 border-t border-blue-400/30 pt-4">
                        <p class="mb-2 text-xs text-blue-200">Versements</p>
                        <div class="mb-4 space-y-2">
                            <div v-for="v in versements" :key="v.id">
                                <div class="flex items-center justify-between rounded-lg bg-white/10 px-3 py-2 text-xs">
                                    <span>{{ date(v.dateVersement) }}</span>
                                    <span>{{ montant(v.montant) }}</span>
                                    <span :class="v.statut === 'Validée' ? 'text-green-400' : 'text-amber-400'">{{ v.statut }}</span>
                                </div>
                                <p class="px-2 text-[10px] text-blue-200">
                                    {{ v.numeroRecu }} · {{ v.modePaiement }}<template v-if="v.reference"> · {{ v.reference }}</template>
                                    <button v-if="aRole('admin', 'super_admin')" class="ml-1 cursor-pointer underline" @click="soumettre(() => telecharger('genererPdf', { type: 'recu', id: v.id }))">reçu PDF</button>
                                    <button
                                        v-if="aRole('admin', 'super_admin')"
                                        type="button"
                                        class="ml-2 cursor-pointer underline"
                                        :disabled="envoi || v.statut !== 'Validée' || !emailEtudiantValide"
                                        title="Envoyer le reçu par e-mail (versement validé)"
                                        @click="envoyerDocument('recu', v.id, 'le reçu', selectionne.email)"
                                    >Envoyer</button>
                                </p>
                            </div>
                            <p v-if="!versements.length" class="text-xs text-blue-200">Aucun versement.</p>
                        </div>
                        <form class="space-y-2" @submit.prevent="ajouterVersement">
                            <p class="text-xs text-blue-200">Ajouter un versement</p>
                            <div class="flex gap-2">
                                <input v-model.number="versement.montant" type="number" min="1" placeholder="Montant" class="w-1/2 rounded-lg text-xs text-gray-900" required />
                                <input v-model="versement.dateVersement" type="date" class="w-1/2 rounded-lg text-xs text-gray-900" required aria-label="Date du versement" />
                            </div>
                            <select v-model="versement.statut" class="w-full rounded-lg text-xs text-gray-900" aria-label="Statut"><option>Validée</option><option>En attente</option></select>
                            <div class="flex gap-2">
                                <select v-model="versement.modePaiement" class="w-1/2 rounded-lg text-xs text-gray-900" aria-label="Mode de paiement"><option v-for="m in MODES_PAIEMENT" :key="m">{{ m }}</option></select>
                                <input v-model="versement.reference" placeholder="Référence (facultatif)" class="w-1/2 rounded-lg text-xs text-gray-900" maxlength="100" />
                            </div>
                            <textarea v-model="versement.note" placeholder="Note (facultatif)" class="w-full rounded-lg text-xs text-gray-900" maxlength="1000"></textarea>
                            <button class="bouton w-full bg-amber-500 py-2 text-xs text-white hover:bg-amber-600" :disabled="envoi">+ Ajouter le versement</button>
                        </form>
                    </div>
                </template>
                <p v-else class="mt-4 text-sm text-blue-200">
                    Cet étudiant n’a pas encore d’inscription.
                    <RouterLink v-if="aRole('admin', 'super_admin')" :to="`/etudiants/${selectionne.id}/inscriptions/nouvelle`" class="text-amber-400 underline">Créer une inscription</RouterLink>
                </p>
            </div>
        </div>

        <div v-else>
            <label class="mb-4 flex items-center gap-3 text-sm text-gray-600">Année académique :
                <select v-model="anneeSynthese" class="champ w-auto"><option v-for="a in annees" :key="a.id" :value="a.id">{{ a.libelle }}</option></select>
            </label>
            <div class="mb-4 grid grid-cols-1 gap-4 sm:grid-cols-3">
                <div class="carte p-4"><p class="text-xs text-gray-500">Inscriptions concernées</p><p class="text-xl font-bold text-insec">{{ carte?.nb ?? 0 }}</p></div>
                <div class="carte p-4"><p class="text-xs text-gray-500">Frais nets facturés</p><p class="text-xl font-bold text-insec">{{ millions(carte?.du) }} M MRU</p></div>
                <div class="carte p-4"><p class="text-xs text-gray-500">Encaissé auprès des étudiants</p><p class="text-xl font-bold text-green-600">{{ millions(carte?.encaisse) }} M MRU</p></div>
            </div>
            <div class="overflow-x-auto rounded-xl bg-white shadow">
                <table class="tableau">
                    <thead><tr><th>Année académique</th><th>Inscriptions</th><th>Montant dû</th><th>Encaissé</th><th>Statut</th></tr></thead>
                    <tbody>
                        <tr v-for="s in synthese.filter((x) => x.nb > 0)" :key="s.id">
                            <td>{{ s.libelle }}</td><td>{{ s.nb }}</td><td>{{ montant(s.du) }}</td><td>{{ montant(s.encaisse) }}</td><td><BadgeStatut :statut="s.statut" /></td>
                        </tr>
                        <tr v-if="!synthese.some((x) => x.nb > 0)"><td colspan="5" class="p-6 text-center text-gray-400">Aucune donnée.</td></tr>
                    </tbody>
                </table>
            </div>
        </div>
    </Chargement>
</template>
