// src/composants/ChampsInscription.vue
<script setup lang="ts">
import { computed, watch } from 'vue';
import { useReferentiel } from '../referentiel';

export interface ValeursInscription {
    formationId: string;
    anneeId: string;
    anneeParcours: number | '';
    dateInscription: string;
    numeroIntec: string;
    statut?: string;
    ueIds: string[];
}

defineProps<{ erreurs: Record<string, string>; avecStatut?: boolean }>();
const valeurs = defineModel<ValeursInscription>({ required: true });
const { formationsActives, annees, ues, formation } = useReferentiel();

const duree = computed(() => formation(valeurs.value.formationId)?.dureeAnnees ?? 3);
const uesProposees = computed(() =>
    ues.value.filter((u) => u.active !== false && u.formationId === valeurs.value.formationId && u.anneeParcours === Number(valeurs.value.anneeParcours)),
);
// Comme dans le formulaire d'origine : changer de diplôme ou d'année décoche les UE devenues incompatibles.
watch(uesProposees, (liste) => {
    const permises = new Set(liste.map((u) => u.id));
    valeurs.value.ueIds = valeurs.value.ueIds.filter((id) => permises.has(id));
});
watch(annees, (liste) => {
    if (!valeurs.value.anneeId && liste[0]) valeurs.value.anneeId = liste[0].id;
}, { immediate: true });

const STATUTS = [['active', 'Active'], ['terminée', 'Terminée'], ['suspendue', 'Suspendue'], ['annulée', 'Annulée']];
</script>

<template>
    <div class="grid gap-4 md:grid-cols-2">
        <label class="etiquette">Diplôme
            <select v-model="valeurs.formationId" class="champ mt-1" required>
                <option value="">Sélectionner…</option>
                <option v-for="f in formationsActives" :key="f.id" :value="f.id">{{ f.code }} — {{ f.libelle }}</option>
            </select>
            <span v-if="erreurs.formationId" class="text-xs text-red-600">{{ erreurs.formationId }}</span>
        </label>
        <label class="etiquette">Année académique
            <select v-model="valeurs.anneeId" class="champ mt-1" required>
                <option v-for="a in annees" :key="a.id" :value="a.id">{{ a.libelle }}</option>
            </select>
        </label>
        <label class="etiquette">Année de parcours
            <select v-model.number="valeurs.anneeParcours" class="champ mt-1" required>
                <option value="">Sélectionner…</option>
                <option v-for="i in duree" :key="i" :value="i">Année {{ i }}</option>
            </select>
        </label>
        <label class="etiquette">Date d’inscription
            <input v-model="valeurs.dateInscription" type="date" class="champ mt-1" required />
        </label>
        <label class="etiquette">N° d’inscription INTEC <span class="text-gray-400">(facultatif)</span>
            <input v-model="valeurs.numeroIntec" class="champ mt-1" maxlength="100" />
        </label>
        <label v-if="avecStatut" class="etiquette">Statut de l’inscription
            <select v-model="valeurs.statut" class="champ mt-1">
                <option v-for="[v, l] in STATUTS" :key="v" :value="v">{{ l }}</option>
            </select>
        </label>
    </div>
    <div class="mt-4">
        <p class="mb-2 text-sm font-medium text-gray-700">UE suivies</p>
        <div class="grid gap-2 rounded-lg border border-gray-200 p-3 md:grid-cols-2">
            <label v-for="ue in uesProposees" :key="ue.id" class="flex gap-2 rounded p-2 text-sm hover:bg-gray-50">
                <input v-model="valeurs.ueIds" type="checkbox" :value="ue.id" class="mt-0.5 rounded border-gray-300" />
                <span><strong>{{ ue.code }}</strong> — {{ ue.libelle }} <span class="text-xs text-gray-500">({{ ue.credits }} ECTS)</span></span>
            </label>
            <p v-if="!uesProposees.length" class="text-sm text-gray-500">Choisissez d’abord le diplôme et l’année de parcours.</p>
        </div>
        <p v-if="erreurs.ueIds" class="mt-1 text-xs text-red-600">{{ erreurs.ueIds }}</p>
    </div>
</template>

// src/components/champs-inscription.tsx
"use client";

import { useState } from "react";

type UeOption = { id: number; code: string; libelle: string; credits: number; anneeParcours: number | null };
type FormationOption = { id: number; code: string | null; libelle: string | null; nom: string; dureeAnnees: number; ues: UeOption[] };

const STATUTS = [
  ["active", "Active"],
  ["terminée", "Terminée"],
  ["suspendue", "Suspendue"],
  ["annulée", "Annulée"],
] as const;

/** Champs d'inscription : les UE proposées dépendent du diplôme et de l'année de parcours choisis. */
export function ChampsInscription({
  formations,
  annees,
  valeurs,
  afficherStatut,
  aujourdhui,
}: {
  formations: FormationOption[];
  annees: { id: number; libelle: string }[];
  valeurs?: {
    formationId: number;
    anneeAcademiqueId: number;
    anneeParcours: number | null;
    dateInscription: string | null;
    numeroInscriptionIntec: string | null;
    statut: string;
    ueIds: number[];
  };
  afficherStatut: boolean;
  aujourdhui: string;
}) {
  const [formationId, setFormationId] = useState(valeurs ? String(valeurs.formationId) : "");
  const [annee, setAnnee] = useState(valeurs?.anneeParcours ? String(valeurs.anneeParcours) : "");
  const [cochees, setCochees] = useState<number[]>(valeurs?.ueIds ?? []);

  const formation = formations.find((f) => String(f.id) === formationId);
  const visibles = formation?.ues.filter((u) => String(u.anneeParcours) === annee) ?? [];
  const idsVisibles = new Set(visibles.map((u) => u.id));
  const maxAnnees = formation?.dureeAnnees ?? 3;

  return (
    <>
      <div className="grid md:grid-cols-2 gap-4">
        <label className="text-sm text-gray-600">
          Diplôme
          <select
            name="formation_id"
            required
            className="w-full rounded-lg mt-1"
            value={formationId}
            onChange={(e) => {
              setFormationId(e.target.value);
              setCochees([]);
            }}
          >
            <option value="">Sélectionner…</option>
            {formations.map((f) => (
              <option key={f.id} value={f.id}>
                {f.code} — {f.libelle}
              </option>
            ))}
          </select>
        </label>
        <label className="text-sm text-gray-600">
          Année académique
          <select name="annee_academique_id" required className="w-full rounded-lg mt-1" defaultValue={valeurs?.anneeAcademiqueId}>
            {annees.map((a) => (
              <option key={a.id} value={a.id}>
                {a.libelle}
              </option>
            ))}
          </select>
        </label>
        <label className="text-sm text-gray-600">
          Année de parcours
          <select
            name="annee_parcours"
            required
            className="w-full rounded-lg mt-1"
            value={annee}
            onChange={(e) => {
              setAnnee(e.target.value);
              setCochees([]);
            }}
          >
            <option value="">Sélectionner…</option>
            {Array.from({ length: Math.max(maxAnnees, 1) }, (_, i) => i + 1).map((i) => (
              <option key={i} value={i}>
                Année {i}
              </option>
            ))}
          </select>
        </label>
        <label className="text-sm text-gray-600">
          Date d’inscription
          <input type="date" name="date_inscription" required className="w-full rounded-lg mt-1" defaultValue={valeurs?.dateInscription ?? aujourdhui} />
        </label>
        <label className="text-sm text-gray-600">
          N° d’inscription INTEC <span className="text-gray-400">(facultatif)</span>
          <input name="numero_inscription_intec" className="w-full rounded-lg mt-1" defaultValue={valeurs?.numeroInscriptionIntec ?? ""} />
        </label>
        {afficherStatut && (
          <label className="text-sm text-gray-600">
            Statut de l’inscription
            <select name="statut" className="w-full rounded-lg mt-1" defaultValue={valeurs?.statut ?? "active"}>
              {STATUTS.map(([v, l]) => (
                <option key={v} value={v}>
                  {l}
                </option>
              ))}
            </select>
          </label>
        )}
      </div>

      <fieldset>
        <legend className="text-sm font-medium text-gray-700 mb-2">UE suivies</legend>
        <div className="grid md:grid-cols-2 gap-2 rounded-lg border border-gray-200 p-3">
          {visibles.map((ue) => (
            <label key={ue.id} className="flex gap-2 rounded p-2 hover:bg-gray-50 text-sm">
              <input
                type="checkbox"
                name="ue_ids"
                value={ue.id}
                className="mt-0.5 rounded"
                checked={cochees.includes(ue.id)}
                onChange={(e) =>
                  setCochees((c) => (e.target.checked ? [...c, ue.id] : c.filter((x) => x !== ue.id)))
                }
              />
              <span>
                <strong>{ue.code}</strong> — {ue.libelle} <span className="text-xs text-gray-500">({ue.credits} ECTS)</span>
              </span>
            </label>
          ))}
          {visibles.length === 0 && <p className="text-sm text-gray-500">Choisissez d’abord le diplôme et l’année de parcours.</p>}
          {visibles.length > 0 && (
            <button
              type="button"
              className="md:col-span-2 text-left text-xs text-insec font-semibold"
              onClick={() => setCochees(cochees.filter((id) => idsVisibles.has(id)).length === visibles.length ? [] : visibles.map((u) => u.id))}
            >
              Tout cocher / décocher
            </button>
          )}
        </div>
      </fieldset>
    </>
  );
}
